# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'staff_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_staff_main_window(object):
    def setupUi(self, staff_main_window):
        staff_main_window.setObjectName("staff_main_window")
        staff_main_window.resize(1920, 1080)
        staff_main_window.setStyleSheet("background-color: rgb(19, 81, 99);")
        self.verticalLayoutWidget = QtWidgets.QWidget(staff_main_window)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 70, 1921, 81))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textBrowser = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(28)
        font.setBold(False)
        font.setUnderline(False)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("background-color: rgb(19, 81, 99);\n"
"border: none;\n"
"border-color: rgb(19, 81, 99);\n"
"")
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.main_screen_button_idcard = QtWidgets.QPushButton(staff_main_window)
        self.main_screen_button_idcard.setGeometry(QtCore.QRect(1270, 520, 609, 251))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        self.main_screen_button_idcard.setFont(font)
        self.main_screen_button_idcard.setStyleSheet("font: 75 18pt \"Microsoft JhengHei UI\";\n"
"background-color: rgb(55, 139, 164);\n"
"color: rgb(255, 255, 255);\n"
"QPushButton {\n"
"    border: none;\n"
"    border-radius: 50px;\n"
"}\n"
"QPushButton:pressed {\n"
"    color: rgb(19, 81, 99);\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/ID_CARD.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.main_screen_button_idcard.setIcon(icon)
        self.main_screen_button_idcard.setIconSize(QtCore.QSize(150, 150))
        self.main_screen_button_idcard.setObjectName("main_screen_button_idcard")
        self.main_screen_button_barcode = QtWidgets.QPushButton(staff_main_window)
        self.main_screen_button_barcode.setGeometry(QtCore.QRect(655, 520, 609, 251))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_screen_button_barcode.sizePolicy().hasHeightForWidth())
        self.main_screen_button_barcode.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        self.main_screen_button_barcode.setFont(font)
        self.main_screen_button_barcode.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.main_screen_button_barcode.setStyleSheet("font: 75 18pt \"Microsoft JhengHei UI\";\n"
"background-color: rgb(55, 139, 164);\n"
"color: rgb(255, 255, 255);\n"
"QPushButton {\n"
"    border: none;\n"
"    border-radius: 50px;\n"
"}\n"
"QPushButton:pressed {\n"
"    color: rgb(19, 81, 99);\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/BARCODE.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.main_screen_button_barcode.setIcon(icon1)
        self.main_screen_button_barcode.setIconSize(QtCore.QSize(150, 150))
        self.main_screen_button_barcode.setObjectName("main_screen_button_barcode")
        self.main_screen_button_manual = QtWidgets.QPushButton(staff_main_window)
        self.main_screen_button_manual.setGeometry(QtCore.QRect(40, 520, 609, 251))
        self.main_screen_button_manual.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        self.main_screen_button_manual.setFont(font)
        self.main_screen_button_manual.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.main_screen_button_manual.setStyleSheet("font: 75 18pt \"Microsoft JhengHei UI\";\n"
"background-color: rgb(55, 139, 164);\n"
"color: rgb(255, 255, 255);\n"
"QPushButton {\n"
"    border: none;\n"
"    border-radius: 50px;\n"
"}\n"
"QPushButton:pressed {\n"
"    color: rgb(19, 81, 99);\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/MANUAL.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.main_screen_button_manual.setIcon(icon2)
        self.main_screen_button_manual.setIconSize(QtCore.QSize(150, 150))
        self.main_screen_button_manual.setObjectName("main_screen_button_manual")

        self.retranslateUi(staff_main_window)
        QtCore.QMetaObject.connectSlotsByName(staff_main_window)

    def retranslateUi(self, staff_main_window):
        _translate = QtCore.QCoreApplication.translate
        staff_main_window.setWindowTitle(_translate("staff_main_window", "Form"))
        self.textBrowser.setHtml(_translate("staff_main_window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Microsoft JhengHei UI\'; font-size:28pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">輸入員工ID</span></p></body></html>"))
        self.main_screen_button_idcard.setText(_translate("staff_main_window", "插入員工證"))
        self.main_screen_button_barcode.setText(_translate("staff_main_window", "條碼輸入"))
        self.main_screen_button_manual.setText(_translate("staff_main_window", "手動輸入"))
import images_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    staff_main_window = QtWidgets.QWidget()
    ui = Ui_staff_main_window()
    ui.setupUi(staff_main_window)
    staff_main_window.show()
    sys.exit(app.exec_())
