# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'staff_login_window_manual.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_staff_login_window_manual(object):
    def setupUi(self, staff_login_window_manual):
        staff_login_window_manual.setObjectName("staff_login_window_manual")
        staff_login_window_manual.resize(400, 291)

        self.retranslateUi(staff_login_window_manual)
        QtCore.QMetaObject.connectSlotsByName(staff_login_window_manual)

    def retranslateUi(self, staff_login_window_manual):
        _translate = QtCore.QCoreApplication.translate
        staff_login_window_manual.setWindowTitle(_translate("staff_login_window_manual", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    staff_login_window_manual = QtWidgets.QWidget()
    ui = Ui_staff_login_window_manual()
    ui.setupUi(staff_login_window_manual)
    staff_login_window_manual.show()
    sys.exit(app.exec_())
